name: "carbonapi"
arch: "amd64"
platform: "linux"
version: "${MY_APP_VERSION}"
section: "default"
priority: "extra"
maintainer: "Vladimir Smirnov <civil.over@gmail.com>"
description: "carbonapi: replacement for graphite API server"
homepage: "https://github.com/go-graphite/carbonapi"
license: "BSD-2"
contents:
  -
    src: ./usr/bin/carbonapi
    dst: /usr/bin/carbonapi
  -
    src: ./usr/share/carbonapi/carbonapi.example.yaml
    dst: /usr/share/carbonapi/carbonapi.example.yaml
  -
    src: /root/go/src/github.com/go-graphite/carbonapi/contrib/carbonapi/rhel/carbonapi.service
    dst: /etc/systemd/system/carbonapi.service
    type: config|noreplace
    packager: rpm
  -
    src: /root/go/src/github.com/go-graphite/carbonapi/contrib/carbonapi/deb/carbonapi.service
    dst: /etc/systemd/system/carbonapi.service
    type: config|noreplace
    packager: deb
  -
    src: /root/go/src/github.com/go-graphite/carbonapi/contrib/carbonapi/common/carbonapi.env
    dst: /etc/sysconfig/carbonapi
    type: config|noreplace
    packager: rpm
  -
    src: /root/go/src/github.com/go-graphite/carbonapi/contrib/carbonapi/common/carbonapi.env
    dst: /etc/default/carbonapi
    type: config
    packager: deb
  -
    src: /root/go/src/github.com/go-graphite/carbonapi/contrib/carbonapi/rhel/carbonapi.logrotate
    dst: /etc/logrotate.d/carbonapi
    type: config|noreplace
    packager: rpm
  -
    src: /root/go/src/github.com/go-graphite/carbonapi/contrib/carbonapi/deb/carbonapi.logrotate
    dst: /etc/logrotate.d/carbonapi
    type: config
    packager: deb
scripts:
  postinstall: /root/go/src/github.com/go-graphite/carbonapi/contrib/carbonapi/fpm/carbon-user-systemd-reload.sh
overrides:
  deb:
    depends:
      - libcairo2
  rpm:
    depends:
      - cairo
