# This is a basic workflow to help you get started with Actions

name: create-build-images

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      # Runs a single command using the runners shell
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Build ubuntu-22.04 image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker/ubuntu-2204
          tags: ghcr.io/go-graphite/go-graphite-build-ubuntu:22.04
      - name: Build ubuntu-20.04 image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker/ubuntu-2004
          tags: ghcr.io/go-graphite/go-graphite-build-ubuntu:20.04
      - name: Build ubuntu-18.04 image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker/ubuntu-1804
          tags: ghcr.io/go-graphite/go-graphite-build-ubuntu:18.04
      - name: Build debian-bookworm image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker/debian-bookworm
          tags: ghcr.io/go-graphite/go-graphite-build-debian:bookworm
      - name: Build debian-bullseye image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker/debian-bullseye
          tags: ghcr.io/go-graphite/go-graphite-build-debian:bullseye
      - name: Build debian-buster image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker/debian-buster
          tags: ghcr.io/go-graphite/go-graphite-build-debian:buster
      - name: Build rockylinux-8 image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker/rockylinux-8
          tags: ghcr.io/go-graphite/go-graphite-build-rockylinux:8
      - name: Build debian-stretch image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker/centos-7
          tags: ghcr.io/go-graphite/go-graphite-build-centos:7
